apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devsecops-ci-cd-pipeline-prod-project-eks
  region: ap-south-1
  version: "1.32"
  tags:
    owner: kumar-aryan
    environment: training
    project: DevSecOps-CI-CD-Pipeline-Prod-Project
    purpose: hands-on-implementation-of-devsecops-ci-cd-pipeline-using-jenkins-and-eks

availabilityZones:
  - ap-south-1a
  - ap-south-1b

iam:
  withOIDC: true

managedNodeGroups:
  - name: eks-cluster-ng-public
    instanceType: t3.small
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: false

    ssh:
      allow: true
      publicKeyName: "Admin EC2 Jenkins Controller Mumbai Key"

    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        externalDNS: true
        certManager: false
        cloudWatch: false
    labels:
      owner: kumar-aryan
      app: devsecops-ci-cd-pipeline-prod-project
    tags:
      node-type: public-worker
      managed-by: eksctl
